// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/sentinel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromptText    string                 `protobuf:"bytes,1,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCacheRequest) Reset() {
	*x = CheckCacheRequest{}
	mi := &file_proto_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCacheRequest) ProtoMessage() {}

func (x *CheckCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCacheRequest.ProtoReflect.Descriptor instead.
func (*CheckCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCacheRequest) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

type CheckCacheResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsHit           bool                   `protobuf:"varint,1,opt,name=is_hit,json=isHit,proto3" json:"is_hit,omitempty"`
	CachedPayload   string                 `protobuf:"bytes,2,opt,name=cached_payload,json=cachedPayload,proto3" json:"cached_payload,omitempty"`
	SimilarityScore float32                `protobuf:"fixed32,3,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckCacheResponse) Reset() {
	*x = CheckCacheResponse{}
	mi := &file_proto_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCacheResponse) ProtoMessage() {}

func (x *CheckCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCacheResponse.ProtoReflect.Descriptor instead.
func (*CheckCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCacheResponse) GetIsHit() bool {
	if x != nil {
		return x.IsHit
	}
	return false
}

func (x *CheckCacheResponse) GetCachedPayload() string {
	if x != nil {
		return x.CachedPayload
	}
	return ""
}

func (x *CheckCacheResponse) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

var File_proto_sentinel_proto protoreflect.FileDescriptor

const file_proto_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x14proto/sentinel.proto\x12\x05proto\"4\n" +
	"\x11CheckCacheRequest\x12\x1f\n" +
	"\vprompt_text\x18\x01 \x01(\tR\n" +
	"promptText\"}\n" +
	"\x12CheckCacheResponse\x12\x15\n" +
	"\x06is_hit\x18\x01 \x01(\bR\x05isHit\x12%\n" +
	"\x0ecached_payload\x18\x02 \x01(\tR\rcachedPayload\x12)\n" +
	"\x10similarity_score\x18\x03 \x01(\x02R\x0fsimilarityScore2T\n" +
	"\x0fSemanticService\x12A\n" +
	"\n" +
	"CheckCache\x12\x18.proto.CheckCacheRequest\x1a\x19.proto.CheckCacheResponseB\x15Z\x13sentinel/gateway/pbb\x06proto3"

var (
	file_proto_sentinel_proto_rawDescOnce sync.Once
	file_proto_sentinel_proto_rawDescData []byte
)

func file_proto_sentinel_proto_rawDescGZIP() []byte {
	file_proto_sentinel_proto_rawDescOnce.Do(func() {
		file_proto_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentinel_proto_rawDesc), len(file_proto_sentinel_proto_rawDesc)))
	})
	return file_proto_sentinel_proto_rawDescData
}

var file_proto_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sentinel_proto_goTypes = []any{
	(*CheckCacheRequest)(nil),  // 0: proto.CheckCacheRequest
	(*CheckCacheResponse)(nil), // 1: proto.CheckCacheResponse
}
var file_proto_sentinel_proto_depIdxs = []int32{
	0, // 0: proto.SemanticService.CheckCache:input_type -> proto.CheckCacheRequest
	1, // 1: proto.SemanticService.CheckCache:output_type -> proto.CheckCacheResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sentinel_proto_init() }
func file_proto_sentinel_proto_init() {
	if File_proto_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentinel_proto_rawDesc), len(file_proto_sentinel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentinel_proto_goTypes,
		DependencyIndexes: file_proto_sentinel_proto_depIdxs,
		MessageInfos:      file_proto_sentinel_proto_msgTypes,
	}.Build()
	File_proto_sentinel_proto = out.File
	file_proto_sentinel_proto_goTypes = nil
	file_proto_sentinel_proto_depIdxs = nil
}
