// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/sentinel.proto
#ifndef GRPC_proto_2fsentinel_2eproto__INCLUDED
#define GRPC_proto_2fsentinel_2eproto__INCLUDED

#include "proto/sentinel.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace proto {

class SemanticService final {
 public:
  static constexpr char const* service_full_name() {
    return "proto.SemanticService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::proto::CheckCacheResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::CheckCacheResponse>> AsyncCheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::CheckCacheResponse>>(AsyncCheckCacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::CheckCacheResponse>> PrepareAsyncCheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::CheckCacheResponse>>(PrepareAsyncCheckCacheRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::CheckCacheResponse>* AsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::CheckCacheResponse>* PrepareAsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::proto::CheckCacheResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>> AsyncCheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>>(AsyncCheckCacheRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>> PrepareAsyncCheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>>(PrepareAsyncCheckCacheRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, std::function<void(::grpc::Status)>) override;
      void CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>* AsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>* PrepareAsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckCache_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckCache(::grpc::ServerContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckCache() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCache(::grpc::ServerContext* /*context*/, const ::proto::CheckCacheRequest* /*request*/, ::proto::CheckCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckCache(::grpc::ServerContext* context, ::proto::CheckCacheRequest* request, ::grpc::ServerAsyncResponseWriter< ::proto::CheckCacheResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckCache<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckCache() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::proto::CheckCacheRequest, ::proto::CheckCacheResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response) { return this->CheckCache(context, request, response); }));}
    void SetMessageAllocatorFor_CheckCache(
        ::grpc::MessageAllocator< ::proto::CheckCacheRequest, ::proto::CheckCacheResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::proto::CheckCacheRequest, ::proto::CheckCacheResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCache(::grpc::ServerContext* /*context*/, const ::proto::CheckCacheRequest* /*request*/, ::proto::CheckCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckCache(
      ::grpc::CallbackServerContext* /*context*/, const ::proto::CheckCacheRequest* /*request*/, ::proto::CheckCacheResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckCache<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckCache() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCache(::grpc::ServerContext* /*context*/, const ::proto::CheckCacheRequest* /*request*/, ::proto::CheckCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckCache() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCache(::grpc::ServerContext* /*context*/, const ::proto::CheckCacheRequest* /*request*/, ::proto::CheckCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckCache(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckCache() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckCache(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCache(::grpc::ServerContext* /*context*/, const ::proto::CheckCacheRequest* /*request*/, ::proto::CheckCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckCache(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckCache : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckCache() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::proto::CheckCacheRequest, ::proto::CheckCacheResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::proto::CheckCacheRequest, ::proto::CheckCacheResponse>* streamer) {
                       return this->StreamedCheckCache(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckCache() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckCache(::grpc::ServerContext* /*context*/, const ::proto::CheckCacheRequest* /*request*/, ::proto::CheckCacheResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckCache(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::proto::CheckCacheRequest,::proto::CheckCacheResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckCache<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckCache<Service > StreamedService;
};

}  // namespace proto


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_proto_2fsentinel_2eproto__INCLUDED
