// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/sentinel.proto
// Protobuf C++ Version: 6.33.4

#ifndef proto_2fsentinel_2eproto_2epb_2eh
#define proto_2fsentinel_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fsentinel_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fsentinel_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fsentinel_2eproto;
}  // extern "C"
namespace proto {
class CheckCacheRequest;
struct CheckCacheRequestDefaultTypeInternal;
extern CheckCacheRequestDefaultTypeInternal _CheckCacheRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CheckCacheRequest_class_data_;
class CheckCacheResponse;
struct CheckCacheResponseDefaultTypeInternal;
extern CheckCacheResponseDefaultTypeInternal _CheckCacheResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CheckCacheResponse_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class CheckCacheResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CheckCacheResponse) */ {
 public:
  inline CheckCacheResponse() : CheckCacheResponse(nullptr) {}
  ~CheckCacheResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CheckCacheResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CheckCacheResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CheckCacheResponse(::google::protobuf::internal::ConstantInitialized);

  inline CheckCacheResponse(const CheckCacheResponse& from) : CheckCacheResponse(nullptr, from) {}
  inline CheckCacheResponse(CheckCacheResponse&& from) noexcept
      : CheckCacheResponse(nullptr, ::std::move(from)) {}
  inline CheckCacheResponse& operator=(const CheckCacheResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CheckCacheResponse& operator=(CheckCacheResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CheckCacheResponse& default_instance() {
    return *reinterpret_cast<const CheckCacheResponse*>(
        &_CheckCacheResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CheckCacheResponse& a, CheckCacheResponse& b) { a.Swap(&b); }
  inline void Swap(CheckCacheResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CheckCacheResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CheckCacheResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CheckCacheResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CheckCacheResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CheckCacheResponse& from) { CheckCacheResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CheckCacheResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CheckCacheResponse"; }

  explicit CheckCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CheckCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CheckCacheResponse& from);
  CheckCacheResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CheckCacheResponse&& from) noexcept
      : CheckCacheResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCachedPayloadFieldNumber = 2,
    kIsHitFieldNumber = 1,
    kSimilarityScoreFieldNumber = 3,
  };
  // string cached_payload = 2;
  void clear_cached_payload() ;
  const ::std::string& cached_payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cached_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cached_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cached_payload();
  void set_allocated_cached_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cached_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cached_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cached_payload();

  public:
  // bool is_hit = 1;
  void clear_is_hit() ;
  bool is_hit() const;
  void set_is_hit(bool value);

  private:
  bool _internal_is_hit() const;
  void _internal_set_is_hit(bool value);

  public:
  // float similarity_score = 3;
  void clear_similarity_score() ;
  float similarity_score() const;
  void set_similarity_score(float value);

  private:
  float _internal_similarity_score() const;
  void _internal_set_similarity_score(float value);

  public:
  // @@protoc_insertion_point(class_scope:proto.CheckCacheResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 47,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CheckCacheResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cached_payload_;
    bool is_hit_;
    float similarity_score_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fsentinel_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CheckCacheResponse_class_data_;
// -------------------------------------------------------------------

class CheckCacheRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CheckCacheRequest) */ {
 public:
  inline CheckCacheRequest() : CheckCacheRequest(nullptr) {}
  ~CheckCacheRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CheckCacheRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CheckCacheRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CheckCacheRequest(::google::protobuf::internal::ConstantInitialized);

  inline CheckCacheRequest(const CheckCacheRequest& from) : CheckCacheRequest(nullptr, from) {}
  inline CheckCacheRequest(CheckCacheRequest&& from) noexcept
      : CheckCacheRequest(nullptr, ::std::move(from)) {}
  inline CheckCacheRequest& operator=(const CheckCacheRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CheckCacheRequest& operator=(CheckCacheRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CheckCacheRequest& default_instance() {
    return *reinterpret_cast<const CheckCacheRequest*>(
        &_CheckCacheRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CheckCacheRequest& a, CheckCacheRequest& b) { a.Swap(&b); }
  inline void Swap(CheckCacheRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CheckCacheRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CheckCacheRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CheckCacheRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CheckCacheRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CheckCacheRequest& from) { CheckCacheRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CheckCacheRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CheckCacheRequest"; }

  explicit CheckCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CheckCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CheckCacheRequest& from);
  CheckCacheRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CheckCacheRequest&& from) noexcept
      : CheckCacheRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPromptTextFieldNumber = 1,
  };
  // string prompt_text = 1;
  void clear_prompt_text() ;
  const ::std::string& prompt_text() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_prompt_text(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_prompt_text();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_prompt_text();
  void set_allocated_prompt_text(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_prompt_text() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_prompt_text(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_prompt_text();

  public:
  // @@protoc_insertion_point(class_scope:proto.CheckCacheRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CheckCacheRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr prompt_text_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fsentinel_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CheckCacheRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CheckCacheRequest

// string prompt_text = 1;
inline void CheckCacheRequest::clear_prompt_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prompt_text_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CheckCacheRequest::prompt_text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CheckCacheRequest.prompt_text)
  return _internal_prompt_text();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CheckCacheRequest::set_prompt_text(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.prompt_text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CheckCacheRequest.prompt_text)
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheRequest::mutable_prompt_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_prompt_text();
  // @@protoc_insertion_point(field_mutable:proto.CheckCacheRequest.prompt_text)
  return _s;
}
inline const ::std::string& CheckCacheRequest::_internal_prompt_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prompt_text_.Get();
}
inline void CheckCacheRequest::_internal_set_prompt_text(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prompt_text_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheRequest::_internal_mutable_prompt_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.prompt_text_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CheckCacheRequest::release_prompt_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CheckCacheRequest.prompt_text)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.prompt_text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.prompt_text_.Set("", GetArena());
  }
  return released;
}
inline void CheckCacheRequest::set_allocated_prompt_text(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.prompt_text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.prompt_text_.IsDefault()) {
    _impl_.prompt_text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CheckCacheRequest.prompt_text)
}

// -------------------------------------------------------------------

// CheckCacheResponse

// bool is_hit = 1;
inline void CheckCacheResponse::clear_is_hit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_hit_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool CheckCacheResponse::is_hit() const {
  // @@protoc_insertion_point(field_get:proto.CheckCacheResponse.is_hit)
  return _internal_is_hit();
}
inline void CheckCacheResponse::set_is_hit(bool value) {
  _internal_set_is_hit(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.CheckCacheResponse.is_hit)
}
inline bool CheckCacheResponse::_internal_is_hit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_hit_;
}
inline void CheckCacheResponse::_internal_set_is_hit(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_hit_ = value;
}

// string cached_payload = 2;
inline void CheckCacheResponse::clear_cached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cached_payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CheckCacheResponse::cached_payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CheckCacheResponse.cached_payload)
  return _internal_cached_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CheckCacheResponse::set_cached_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.cached_payload_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CheckCacheResponse.cached_payload)
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheResponse::mutable_cached_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_cached_payload();
  // @@protoc_insertion_point(field_mutable:proto.CheckCacheResponse.cached_payload)
  return _s;
}
inline const ::std::string& CheckCacheResponse::_internal_cached_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cached_payload_.Get();
}
inline void CheckCacheResponse::_internal_set_cached_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cached_payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheResponse::_internal_mutable_cached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cached_payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CheckCacheResponse::release_cached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CheckCacheResponse.cached_payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.cached_payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cached_payload_.Set("", GetArena());
  }
  return released;
}
inline void CheckCacheResponse::set_allocated_cached_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.cached_payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cached_payload_.IsDefault()) {
    _impl_.cached_payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CheckCacheResponse.cached_payload)
}

// float similarity_score = 3;
inline void CheckCacheResponse::clear_similarity_score() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.similarity_score_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float CheckCacheResponse::similarity_score() const {
  // @@protoc_insertion_point(field_get:proto.CheckCacheResponse.similarity_score)
  return _internal_similarity_score();
}
inline void CheckCacheResponse::set_similarity_score(float value) {
  _internal_set_similarity_score(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.CheckCacheResponse.similarity_score)
}
inline float CheckCacheResponse::_internal_similarity_score() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.similarity_score_;
}
inline void CheckCacheResponse::_internal_set_similarity_score(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.similarity_score_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fsentinel_2eproto_2epb_2eh
