// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/sentinel.proto

#include "proto/sentinel.pb.h"
#include "proto/sentinel.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace proto {

static const char* SemanticService_method_names[] = {
  "/proto.SemanticService/CheckCache",
};

std::unique_ptr< SemanticService::Stub> SemanticService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SemanticService::Stub> stub(new SemanticService::Stub(channel, options));
  return stub;
}

SemanticService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckCache_(SemanticService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SemanticService::Stub::CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::proto::CheckCacheResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::proto::CheckCacheRequest, ::proto::CheckCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckCache_, context, request, response);
}

void SemanticService::Stub::async::CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::proto::CheckCacheRequest, ::proto::CheckCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckCache_, context, request, response, std::move(f));
}

void SemanticService::Stub::async::CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckCache_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>* SemanticService::Stub::PrepareAsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::proto::CheckCacheResponse, ::proto::CheckCacheRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckCache_, context, request);
}

::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>* SemanticService::Stub::AsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckCacheRaw(context, request, cq);
  result->StartCall();
  return result;
}

SemanticService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SemanticService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SemanticService::Service, ::proto::CheckCacheRequest, ::proto::CheckCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SemanticService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::CheckCacheRequest* req,
             ::proto::CheckCacheResponse* resp) {
               return service->CheckCache(ctx, req, resp);
             }, this)));
}

SemanticService::Service::~Service() {
}

::grpc::Status SemanticService::Service::CheckCache(::grpc::ServerContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace proto
#include <grpcpp/ports_undef.inc>

